name: Buildozer Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              python3-pip \
              build-essential \
              git \
              python3 \
              python3-dev \
              ffmpeg \
              libsdl2-dev \
              libsdl2-image-dev \
              libsdl2-mixer-dev \
              libsdl2-ttf-dev \
              libportmidi-dev \
              libswscale-dev \
              libavformat-dev \
              libavcodec-dev \
              zlib1g-dev
          pip install buildozer cython==0.29.34

      - name: Build with Buildozer
        run: |
          # Crea un buildozer.spec básico
          cat > buildozer.spec <<EOF
          [app]
          title = Asistente Cognitivo
          package.name = asistente
          package.domain = org.test
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas,json,ttf
          version = 0.1
          requirements = -r requirements.txt
          orientation = portrait
          android.permissions = CAMERA, RECORD_AUDIO, INTERNET
          android.arch = armeabi-v7a,arm64-v8a
          [buildozer]
          log_level = 2
          warn_on_root = 1
          EOF
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: asistente-cognitivo.apk
          path: bin/*.apk
