name: Buildozer Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          # Comando para construir el APK
          command: buildozer -v android debug
          
          # Contenido del archivo buildozer.spec
          buildozer_spec: |
            [app]
            title = Asistente Cognitivo
            package.name = asistente
            package.domain = org.test
            source.dir = .
            source.include_exts = py,png,jpg,kv,atlas,json,ttf
            version = 0.1
            requirements = -r requirements.txt
            orientation = portrait
            android.permissions = CAMERA, RECORD_AUDIO, INTERNET
            android.archs = armeabi-v7a, arm64-v8a
            
            [buildozer]
            log_level = 2
            warn_on_root = 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: asistente-cognitivo.apk
          path: bin/*.apk
